# Site settings
title: बचत
email: knamdeo88@gmail.com
description: Track your income, expenses and investment and take better financial decisions.
baseurl: "/eventually-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://bachat.money" # the base hostname & protocol for your site

# Social settings
linkedin_url: https://www.linkedin.com/company/bachat-money
twitter_url: https://twitter.com/bachat_money
facebook_url:
instagram_url:

# Build settings
markdown: kramdown
